import React, { useState } from 'react';
import { Location, InventoryItem, ConsumptionRecord, AIPredictionAlert } from '../types/schema';
import {
  TrendingUp,
  AlertTriangle,
  Zap,
  Plus,
  Calendar,
  Package,
  ArrowRight,
  ShieldAlert,
  BarChart3
} from 'lucide-react';

interface ConsumptionViewProps {
  locations: Location[];
  inventory: InventoryItem[];
  consumption: ConsumptionRecord[];
  onOpenAddConsumptionModal: () => void;
  onAutoGenerateDispatch: (locationId: string, supplyType: string, recommendedQty: number) => void;
}

export const ConsumptionView: React.FC<ConsumptionViewProps> = ({
  locations,
  inventory,
  consumption,
  onOpenAddConsumptionModal,
  onAutoGenerateDispatch
}) => {
  // Compute AI Stockout Predictive Alerts
  const aiPredictions: AIPredictionAlert[] = inventory.map(item => {
    const loc = locations.find(l => l.location_id === item.location_id);
    const locName = loc ? loc.name : 'Unknown Base';

    // Find consumption records for this location & supply_type
    const matchingConsumption = consumption.filter(
      c => c.location_id === item.location_id && c.supply_type === item.supply_type
    );

    // Calculate average daily burn rate (fallback default burn rates if minimal log history)
    let dailyBurnRate = 50; // default baseline
    if (matchingConsumption.length > 0) {
      const totalConsumed = matchingConsumption.reduce((sum, c) => sum + Number(c.quantity_consumed), 0);
      dailyBurnRate = Math.max(totalConsumed / matchingConsumption.length, 1);
    } else {
      // Estimated baseline burn rate based on supply type
      if (item.supply_type.includes('Rations')) dailyBurnRate = 250;
      if (item.supply_type.includes('Fuel') || item.supply_type.includes('Diesel')) dailyBurnRate = 85;
      if (item.supply_type.includes('Ammunition')) dailyBurnRate = 120;
      if (item.supply_type.includes('Medical')) dailyBurnRate = 30;
    }

    const daysRemaining = Math.floor(item.quantity / dailyBurnRate);

    let riskLevel: 'CRITICAL' | 'WARNING' | 'STABLE' = 'STABLE';
    if (daysRemaining <= 7 || item.quantity < item.safety_stock) {
      riskLevel = 'CRITICAL';
    } else if (daysRemaining <= 15) {
      riskLevel = 'WARNING';
    }

    let recommendedAction = `Maintain standard monitoring. (${daysRemaining} days supply remaining).`;
    if (riskLevel === 'CRITICAL') {
      const deficit = Math.max(item.safety_stock * 2 - item.quantity, dailyBurnRate * 14);
      recommendedAction = `CRITICAL: Stockout predicted in ${daysRemaining} days! Immediately dispatch ${Math.round(deficit)} ${item.unit} from Command Depot.`;
    } else if (riskLevel === 'WARNING') {
      recommendedAction = `WARNING: Stock drops below safety threshold in ${daysRemaining} days. Schedule logistics convoy within 48 hours.`;
    }

    return {
      id: item.inventory_id,
      location_name: locName,
      supply_type: item.supply_type,
      current_quantity: item.quantity,
      daily_burn_rate: Math.round(dailyBurnRate),
      days_remaining: daysRemaining,
      critical_threshold: item.safety_stock,
      risk_level: riskLevel,
      recommended_action: recommendedAction
    };
  });

  const criticalPredictions = aiPredictions.filter(p => p.risk_level === 'CRITICAL');
  const warningPredictions = aiPredictions.filter(p => p.risk_level === 'WARNING');

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Header Banner */}
      <div className="glass-panel" style={{ padding: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <TrendingUp size={22} color="#eab308" />
            <h2 className="font-heading" style={{ fontSize: '1.4rem', color: '#fff', letterSpacing: '0.05em' }}>
              CONSUMPTION LOGS & AI PREDICTIVE STOCKOUT FORECAST (`public.consumption`)
            </h2>
          </div>
          <p style={{ fontSize: '0.83rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            Predictive AI models calculate daily burn rates to prevent forward operating stockouts.
          </p>
        </div>

        <button onClick={onOpenAddConsumptionModal} className="btn-primary">
          <Plus size={16} /> LOG DAILY CONSUMPTION
        </button>
      </div>

      {/* AI Risk Summary Dashboard Cards */}
      <div className="grid-3">
        <div className="glass-panel" style={{ padding: '20px', borderLeft: '4px solid #ef4444' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>CRITICAL RISK FORECASTS</span>
            <ShieldAlert size={20} color="#ef4444" />
          </div>
          <div className="font-heading font-mono" style={{ fontSize: '2rem', fontWeight: 700, color: '#ef4444', marginTop: '6px' }}>
            {criticalPredictions.length} <span style={{ fontSize: '0.9rem', color: 'var(--text-dim)' }}>BASES AT RISK</span>
          </div>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-dim)', marginTop: '4px' }}>
            Predicted stockout within 7 days unless replenished.
          </p>
        </div>

        <div className="glass-panel" style={{ padding: '20px', borderLeft: '4px solid #f97316' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>WARNING THRESHOLD</span>
            <AlertTriangle size={20} color="#f97316" />
          </div>
          <div className="font-heading font-mono" style={{ fontSize: '2rem', fontWeight: 700, color: '#f97316', marginTop: '6px' }}>
            {warningPredictions.length} <span style={{ fontSize: '0.9rem', color: 'var(--text-dim)' }}>BASES WATCHLIST</span>
          </div>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-dim)', marginTop: '4px' }}>
            Estimated 7 to 15 days supply buffer remaining.
          </p>
        </div>

        <div className="glass-panel" style={{ padding: '20px', borderLeft: '4px solid #10b981' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>OPTIMAL RESERVES</span>
            <BarChart3 size={20} color="#10b981" />
          </div>
          <div className="font-heading font-mono" style={{ fontSize: '2rem', fontWeight: 700, color: '#10b981', marginTop: '6px' }}>
            {aiPredictions.length - criticalPredictions.length - warningPredictions.length}{' '}
            <span style={{ fontSize: '0.9rem', color: 'var(--text-dim)' }}>STABLE BASES</span>
          </div>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-dim)', marginTop: '4px' }}>
            Operating at &gt;15 days stock capacity.
          </p>
        </div>
      </div>

      {/* AI Stockout Prediction Cards */}
      <div className="glass-panel" style={{ padding: '20px' }}>
        <h3 className="font-heading" style={{ fontSize: '1.2rem', color: '#eab308', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Zap size={18} color="#eab308" className="animate-pulse-glow" /> AI PREDICTIVE STOCKOUT FORECAST & REPLENISHMENT ADVISORY
        </h3>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          {aiPredictions.map(pred => {
            const isCritical = pred.risk_level === 'CRITICAL';
            const isWarning = pred.risk_level === 'WARNING';
            const itemObj = inventory.find(i => i.inventory_id === pred.id);

            return (
              <div
                key={pred.id}
                style={{
                  background: 'rgba(6, 11, 17, 0.7)',
                  borderRadius: '10px',
                  padding: '16px',
                  border: isCritical ? '1px solid rgba(239, 68, 68, 0.4)' : isWarning ? '1px solid rgba(249, 115, 22, 0.4)' : '1px solid rgba(255, 255, 255, 0.06)',
                  display: 'grid',
                  gridTemplateColumns: '1fr 200px 180px',
                  gap: '16px',
                  alignItems: 'center'
                }}
              >
                {/* Details */}
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <h4 className="font-heading" style={{ fontSize: '1.1rem', color: '#fff' }}>
                      {pred.location_name}
                    </h4>
                    {isCritical ? (
                      <span className="badge badge-danger">CRITICAL STOCKOUT RISK</span>
                    ) : isWarning ? (
                      <span className="badge badge-warning">MODERATE RISK</span>
                    ) : (
                      <span className="badge badge-success">OPTIMAL</span>
                    )}
                  </div>
                  <div style={{ fontSize: '0.88rem', color: '#eab308', marginTop: '2px', fontWeight: 600 }}>
                    {pred.supply_type}
                  </div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '6px' }}>
                    {pred.recommended_action}
                  </div>
                </div>

                {/* Days remaining badge */}
                <div style={{ textAlign: 'center', background: 'rgba(255, 255, 255, 0.03)', padding: '12px', borderRadius: '8px' }}>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>ESTIMATED DAYS REMAINING</div>
                  <div className="font-mono" style={{ fontSize: '1.6rem', fontWeight: 700, color: isCritical ? '#ef4444' : isWarning ? '#f97316' : '#10b981' }}>
                    {pred.days_remaining} <span style={{ fontSize: '0.8rem' }}>DAYS</span>
                  </div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginTop: '2px' }}>
                    Burn: ~{pred.daily_burn_rate} / day
                  </div>
                </div>

                {/* Dispatch Trigger Button */}
                <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                  {(isCritical || isWarning) && itemObj ? (
                    <button
                      onClick={() =>
                        onAutoGenerateDispatch(
                          itemObj.location_id,
                          itemObj.supply_type,
                          Math.max(itemObj.safety_stock * 2 - itemObj.quantity, 500)
                        )
                      }
                      className="btn-primary"
                      style={{ fontSize: '0.82rem', padding: '10px 14px' }}
                    >
                      <Zap size={14} /> AUTO-CREATE DISPATCH
                    </button>
                  ) : (
                    <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>✓ Buffer Adequate</span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Recent Consumption Records Table */}
      <div className="glass-panel" style={{ padding: '20px' }}>
        <h3 className="font-heading" style={{ fontSize: '1.1rem', color: '#fff', marginBottom: '14px' }}>
          DAILY CONSUMPTION LOG HISTORY (`public.consumption`)
        </h3>

        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.88rem' }}>
          <thead>
            <tr style={{ background: 'rgba(6, 11, 17, 0.8)', borderBottom: '1px solid rgba(255, 255, 255, 0.1)', color: '#9ca3af', fontFamily: 'var(--font-heading)' }}>
              <th style={{ padding: '10px 14px' }}>DATE</th>
              <th style={{ padding: '10px 14px' }}>BASE LOCATION</th>
              <th style={{ padding: '10px 14px' }}>SUPPLY TYPE</th>
              <th style={{ padding: '10px 14px' }}>QUANTITY CONSUMED</th>
            </tr>
          </thead>
          <tbody>
            {consumption.map(c => {
              const loc = locations.find(l => l.location_id === c.location_id);
              return (
                <tr key={c.id} style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.05)' }}>
                  <td style={{ padding: '12px 14px' }} className="font-mono">{c.consumption_date}</td>
                  <td style={{ padding: '12px 14px', fontWeight: 600, color: '#fff' }}>{loc ? loc.name : c.location_id}</td>
                  <td style={{ padding: '12px 14px', color: '#eab308' }}>{c.supply_type}</td>
                  <td style={{ padding: '12px 14px' }} className="font-mono">
                    <strong style={{ color: '#f97316' }}>{c.quantity_consumed.toLocaleString()}</strong> {c.unit}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
