import React, { useState, useEffect } from 'react';
import { Location, InventoryItem, ConsumptionRecord, LogisticsRoute } from '../types/schema';
import { ForecastResult } from '../types/forecasting';
import { generateDemandForecast } from '../forecasting/forecastingService';
import {
  TrendingUp,
  Brain,
  Calendar,
  AlertTriangle,
  CheckCircle2,
  Package,
  Layers,
  BarChart3,
  Sparkles,
  Zap,
  Info,
  Clock,
  RefreshCw,
  Cpu
} from 'lucide-react';

interface DemandForecastingViewProps {
  locations: Location[];
  inventory: InventoryItem[];
  consumption: ConsumptionRecord[];
  routes: LogisticsRoute[];
  onAutoGenerateDispatch: (locationId: string, supplyType: string, quantity: number) => void;
  onReseedDemoData?: () => void;
}

export const DemandForecastingView: React.FC<DemandForecastingViewProps> = ({
  locations,
  inventory,
  consumption,
  routes,
  onAutoGenerateDispatch,
  onReseedDemoData
}) => {
  // State for user selectors
  const [selectedLocationId, setSelectedLocationId] = useState<string>(locations[0]?.location_id || '');
  const [selectedSupplyType, setSelectedSupplyType] = useState<string>('Extreme Cold Climate Rations (ECC)');
  const [horizonDays, setHorizonDays] = useState<1 | 3 | 7 | 14>(7);
  const [modelVersion, setModelVersion] = useState<'baseline-v1' | 'rf-v1'>('baseline-v1');

  // Forecast result state
  const [forecastResult, setForecastResult] = useState<ForecastResult | null>(null);
  const [isComputing, setIsComputing] = useState<boolean>(false);
  const [hoveredPoint, setHoveredPoint] = useState<{ date: string; value: number; type: 'hist' | 'pred' } | null>(null);

  // Available supply types derived from inventory or consumption
  const availableSupplyTypes = Array.from(
    new Set([
      'Extreme Cold Climate Rations (ECC)',
      'Ammunition 155mm Artillery',
      'Aviation Turbine Fuel (ATF-Winter)',
      'Diesel Winter Grade (-30C)',
      'Medical Plasma & Oxygen Cylinders',
      'High-Altitude Special Clothing (ECC Clothing)',
      ...inventory.map(i => i.supply_type)
    ])
  );

  // Re-run forecasting pipeline whenever user selection changes
  useEffect(() => {
    if (!selectedLocationId || !selectedSupplyType) return;

    let isMounted = true;
    setIsComputing(true);

    generateDemandForecast(
      selectedLocationId,
      selectedSupplyType,
      horizonDays,
      locations,
      inventory,
      consumption,
      routes,
      modelVersion
    ).then(result => {
      if (isMounted) {
        setForecastResult(result);
        setIsComputing(false);
      }
    });

    return () => {
      isMounted = false;
    };
  }, [selectedLocationId, selectedSupplyType, horizonDays, modelVersion, locations, inventory, consumption, routes]);

  const selectedLocObj = locations.find(l => l.location_id === selectedLocationId);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Header Banner */}
      <div className="glass-panel" style={{ padding: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{ background: 'rgba(234, 179, 8, 0.15)', padding: '8px', borderRadius: '8px', border: '1px solid rgba(234, 179, 8, 0.3)' }}>
              <Brain size={24} color="#eab308" className="animate-pulse-glow" />
            </div>
            <div>
              <h2 className="font-heading" style={{ fontSize: '1.4rem', color: '#fff', letterSpacing: '0.05em' }}>
                MODULE 1: AI/ML DEMAND FORECASTING FOR PREDICTIVE LOGISTICS
              </h2>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                Time-series machine learning models predicting supply requirements & inventory shortages across military sectors.
              </p>
            </div>
          </div>
        </div>

        {onReseedDemoData && (
          <button
            onClick={onReseedDemoData}
            className="btn-secondary"
            style={{ fontSize: '0.82rem', padding: '8px 14px' }}
            title="Generate 90 days of synthetic historical consumption data for testing"
          >
            <Sparkles size={14} color="#eab308" /> SEED 90-DAY DEMO HISTORY
          </button>
        )}
      </div>

      {/* Selectors Bar */}
      <div className="glass-panel military-grid-pattern" style={{ padding: '18px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px', alignItems: 'center' }}>
        {/* 1. Location Selector */}
        <div>
          <label className="font-heading" style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}>
            SELECT LOCATION
          </label>
          <select
            value={selectedLocationId}
            onChange={e => setSelectedLocationId(e.target.value)}
            className="input-field font-heading"
            style={{ fontWeight: 600 }}
          >
            {locations.map(loc => (
              <option key={loc.location_id} value={loc.location_id}>
                {loc.name} ({loc.type})
              </option>
            ))}
          </select>
        </div>

        {/* 2. Supply Selector */}
        <div>
          <label className="font-heading" style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}>
            SELECT SUPPLY ITEM
          </label>
          <select
            value={selectedSupplyType}
            onChange={e => setSelectedSupplyType(e.target.value)}
            className="input-field font-heading"
            style={{ fontWeight: 600 }}
          >
            {availableSupplyTypes.map(st => (
              <option key={st} value={st}>
                {st}
              </option>
            ))}
          </select>
        </div>

        {/* 3. Forecast Horizon Selector */}
        <div>
          <label className="font-heading" style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}>
            FORECAST HORIZON
          </label>
          <div style={{ display: 'flex', gap: '6px' }}>
            {([1, 3, 7, 14] as const).map(h => (
              <button
                key={h}
                onClick={() => setHorizonDays(h)}
                className="font-heading"
                style={{
                  flex: 1,
                  padding: '8px 0',
                  borderRadius: '6px',
                  border: horizonDays === h ? '1px solid #eab308' : '1px solid rgba(255, 255, 255, 0.08)',
                  background: horizonDays === h ? 'rgba(234, 179, 8, 0.2)' : 'rgba(6, 11, 17, 0.6)',
                  color: horizonDays === h ? '#eab308' : 'var(--text-muted)',
                  fontWeight: 700,
                  fontSize: '0.88rem',
                  cursor: 'pointer'
                }}
              >
                {h}D
              </button>
            ))}
          </div>
        </div>

        {/* 4. ML Model Selector */}
        <div>
          <label className="font-heading" style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}>
            ML MODEL ALGORITHM
          </label>
          <div style={{ display: 'flex', gap: '6px' }}>
            <button
              onClick={() => setModelVersion('baseline-v1')}
              className="font-heading"
              style={{
                flex: 1,
                padding: '8px 6px',
                borderRadius: '6px',
                border: modelVersion === 'baseline-v1' ? '1px solid #38bdf8' : '1px solid rgba(255, 255, 255, 0.08)',
                background: modelVersion === 'baseline-v1' ? 'rgba(56, 189, 248, 0.18)' : 'rgba(6, 11, 17, 0.6)',
                color: modelVersion === 'baseline-v1' ? '#38bdf8' : 'var(--text-muted)',
                fontWeight: 700,
                fontSize: '0.78rem',
                cursor: 'pointer'
              }}
            >
              BASELINE (WMA)
            </button>

            <button
              onClick={() => setModelVersion('rf-v1')}
              className="font-heading"
              style={{
                flex: 1,
                padding: '8px 6px',
                borderRadius: '6px',
                border: modelVersion === 'rf-v1' ? '1px solid #a855f7' : '1px solid rgba(255, 255, 255, 0.08)',
                background: modelVersion === 'rf-v1' ? 'rgba(168, 85, 247, 0.18)' : 'rgba(6, 11, 17, 0.6)',
                color: modelVersion === 'rf-v1' ? '#c084fc' : 'var(--text-muted)',
                fontWeight: 700,
                fontSize: '0.78rem',
                cursor: 'pointer'
              }}
            >
              RANDOM FOREST (RF)
            </button>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      {isComputing ? (
        <div className="glass-panel" style={{ padding: '60px', textAlign: 'center' }}>
          <RefreshCw size={32} color="#eab308" className="animate-spin" style={{ margin: '0 auto 16px auto' }} />
          <h3 className="font-heading" style={{ color: '#fff', fontSize: '1.2rem' }}>
            EXECUTING TIME-SERIES ML PREDICTION MODEL...
          </h3>
          <p style={{ color: 'var(--text-dim)', fontSize: '0.85rem', marginTop: '6px' }}>
            Building lag features, rolling windows, and evaluating regression residuals.
          </p>
        </div>
      ) : forecastResult?.insufficient_data ? (
        <div className="glass-panel" style={{ padding: '40px', borderLeft: '4px solid #f97316' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
            <AlertTriangle size={24} color="#f97316" />
            <h3 className="font-heading" style={{ fontSize: '1.25rem', color: '#fff' }}>
              FORECAST UNAVAILABLE
            </h3>
          </div>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
            {forecastResult.error_message || 'More historical consumption data is required for this location & supply item.'}
          </p>
          <div style={{ marginTop: '16px' }}>
            <button onClick={onReseedDemoData} className="btn-primary" style={{ fontSize: '0.85rem' }}>
              <Sparkles size={14} /> GENERATE DEMO SYNTHETIC HISTORY DATA
            </button>
          </div>
        </div>
      ) : forecastResult ? (
        <>
          {/* Top 5 Stat KPI Cards (Section 17) */}
          <div className="grid-4" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))' }}>
            {/* 1. Current Inventory */}
            <div className="glass-panel" style={{ padding: '16px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>CURRENT INVENTORY</span>
                <Package size={18} color="#38bdf8" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#fff', marginTop: '6px' }}>
                {forecastResult.current_inventory.toLocaleString()} <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>{forecastResult.unit}</span>
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginTop: '4px' }}>Recorded at base</div>
            </div>

            {/* 2. Predicted N-Day Demand */}
            <div className="glass-panel" style={{ padding: '16px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>PREDICTED {forecastResult.horizon_days}-DAY DEMAND</span>
                <TrendingUp size={18} color="#eab308" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#eab308', marginTop: '6px' }}>
                {forecastResult.total_predicted_demand.toLocaleString()} <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>{forecastResult.unit}</span>
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginTop: '4px' }}>Sum over next {forecastResult.horizon_days} days</div>
            </div>

            {/* 3. Projected Shortage */}
            <div className="glass-panel" style={{ padding: '16px 20px', borderLeft: forecastResult.projected_shortage > 0 ? '4px solid #ef4444' : '1px solid rgba(255,255,255,0.08)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>PROJECTED SHORTAGE</span>
                <AlertTriangle size={18} color={forecastResult.projected_shortage > 0 ? '#ef4444' : '#10b981'} />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: forecastResult.projected_shortage > 0 ? '#ef4444' : '#10b981', marginTop: '6px' }}>
                {forecastResult.projected_shortage.toLocaleString()} <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>{forecastResult.unit}</span>
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                {forecastResult.projected_shortage > 0 ? 'Deficit forecast' : 'No shortage predicted'}
              </div>
            </div>

            {/* 4. Days of Supply */}
            <div className="glass-panel" style={{ padding: '16px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>DAYS OF SUPPLY</span>
                <Clock size={18} color="#a855f7" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#c084fc', marginTop: '6px' }}>
                {forecastResult.days_of_supply !== null ? `${forecastResult.days_of_supply} DAYS` : 'N/A'}
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                Inventory / Avg daily burn
              </div>
            </div>

            {/* 5. Inventory Risk Status */}
            <div className="glass-panel" style={{ padding: '16px 20px', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '8px' }}>INVENTORY STATUS</span>
              {forecastResult.status === 'SHORTAGE' ? (
                <span className="badge badge-danger" style={{ fontSize: '0.9rem', padding: '6px 14px' }}>
                  <AlertTriangle size={14} /> SHORTAGE ALERT
                </span>
              ) : (
                <span className="badge badge-success" style={{ fontSize: '0.9rem', padding: '6px 14px' }}>
                  <CheckCircle2 size={14} /> SUFFICIENT STOCK
                </span>
              )}
            </div>
          </div>

          {/* Interactive SVG Forecast Chart (Section 18) */}
          <div className="glass-panel military-grid-pattern" style={{ padding: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <h3 className="font-heading" style={{ fontSize: '1.2rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <BarChart3 size={18} color="#eab308" /> HISTORICAL CONSUMPTION & AI DEMAND FORECAST CURVE
                </h3>
                <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '2px' }}>
                  Solid cyan line = Recorded history (past 30 days) | Dashed gold line = Predicted future demand | Shaded area = Confidence Interval
                </p>
              </div>

              <div style={{ display: 'flex', gap: '14px', fontSize: '0.78rem' }} className="font-mono">
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#38bdf8' }}>
                  <span style={{ width: '12px', height: '3px', background: '#38bdf8' }}></span> Historical Log
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#eab308' }}>
                  <span style={{ width: '12px', height: '3px', borderTop: '2px dashed #eab308' }}></span> Predicted Forecast
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(234, 179, 8, 0.4)' }}>
                  <span style={{ width: '12px', height: '8px', background: 'rgba(234, 179, 8, 0.25)', borderRadius: '2px' }}></span> Bounds
                </span>
              </div>
            </div>

            {/* SVG Chart */}
            <ForecastChart
              historicalData={forecastResult.historical_data.slice(-25)}
              forecastData={forecastResult.daily_forecast}
              unit={forecastResult.unit}
              onHover={setHoveredPoint}
            />

            {/* Hover Tooltip display */}
            {hoveredPoint && (
              <div style={{ marginTop: '10px', padding: '8px 14px', background: 'rgba(10, 17, 26, 0.9)', border: '1px solid #eab308', borderRadius: '6px', display: 'inline-flex', gap: '12px', fontSize: '0.82rem' }}>
                <span>Date: <strong style={{ color: '#fff' }}>{hoveredPoint.date}</strong></span>
                <span>Type: <strong style={{ color: hoveredPoint.type === 'hist' ? '#38bdf8' : '#eab308' }}>{hoveredPoint.type === 'hist' ? 'Recorded History' : 'Predicted Forecast'}</strong></span>
                <span>Quantity: <strong style={{ color: '#fff' }}>{hoveredPoint.value.toLocaleString()} {forecastResult.unit}</strong></span>
              </div>
            )}
          </div>

          {/* Logistics Decision Support Insight Card (Section 20) */}
          <div className="glass-panel" style={{ padding: '20px', borderLeft: forecastResult.status === 'SHORTAGE' ? '4px solid #ef4444' : '4px solid #10b981' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
              <div>
                <h3 className="font-heading" style={{ fontSize: '1.15rem', color: '#eab308', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Info size={18} color="#eab308" /> LOGISTICS DECISION SUPPORT INSIGHT
                </h3>
                <p style={{ fontSize: '0.92rem', color: '#f3f4f6', lineHeight: 1.5, maxWidth: '900px' }}>
                  {forecastResult.insight_text}
                </p>
              </div>

              {forecastResult.status === 'SHORTAGE' && (
                <button
                  onClick={() =>
                    onAutoGenerateDispatch(
                      forecastResult.location_id,
                      forecastResult.supply_type,
                      forecastResult.projected_shortage
                    )
                  }
                  className="btn-primary"
                  style={{ fontSize: '0.85rem' }}
                >
                  <Zap size={15} /> DISPATCH {forecastResult.projected_shortage.toLocaleString()} {forecastResult.unit} CONVOY
                </button>
              )}
            </div>
          </div>

          {/* Grid of Daily Forecast Table & Model Performance Metrics */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: '20px' }}>
            {/* Daily Forecast Table (Section 19) */}
            <div className="glass-panel" style={{ padding: '20px' }}>
              <h3 className="font-heading" style={{ fontSize: '1.1rem', color: '#fff', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Calendar size={16} color="#38bdf8" /> DAILY FORECAST BREAKDOWN ({forecastResult.horizon_days} DAYS)
              </h3>

              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.86rem' }}>
                  <thead>
                    <tr style={{ background: 'rgba(6, 11, 17, 0.8)', borderBottom: '1px solid rgba(255, 255, 255, 0.1)', color: '#9ca3af', fontFamily: 'var(--font-heading)' }}>
                      <th style={{ padding: '10px 14px' }}>DATE</th>
                      <th style={{ padding: '10px 14px' }}>PREDICTED DEMAND</th>
                      <th style={{ padding: '10px 14px' }}>LOWER BOUND</th>
                      <th style={{ padding: '10px 14px' }}>UPPER BOUND</th>
                      <th style={{ padding: '10px 14px' }}>MODEL CONFIDENCE</th>
                    </tr>
                  </thead>
                  <tbody>
                    {forecastResult.daily_forecast.map(point => (
                      <tr key={point.date} style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.05)' }}>
                        <td style={{ padding: '10px 14px', fontWeight: 600, color: '#fff' }} className="font-mono">
                          {point.date}
                        </td>
                        <td style={{ padding: '10px 14px', color: '#eab308', fontWeight: 700 }} className="font-mono">
                          {point.predicted_quantity.toLocaleString()} {forecastResult.unit}
                        </td>
                        <td style={{ padding: '10px 14px', color: 'var(--text-muted)' }} className="font-mono">
                          {point.lower_bound !== null ? point.lower_bound.toLocaleString() : 'N/A'}
                        </td>
                        <td style={{ padding: '10px 14px', color: 'var(--text-muted)' }} className="font-mono">
                          {point.upper_bound !== null ? point.upper_bound.toLocaleString() : 'N/A'}
                        </td>
                        <td style={{ padding: '10px 14px' }}>
                          {point.confidence !== null ? (
                            <span className="badge badge-info font-mono" style={{ fontSize: '0.7rem' }}>
                              {(point.confidence * 100).toFixed(0)}%
                            </span>
                          ) : (
                            <span style={{ color: 'var(--text-dim)' }}>Null</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Model Evaluation & Performance Metrics (Section 14 & 13) */}
            <div className="glass-panel" style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <div style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '10px' }}>
                <span className="badge badge-purple" style={{ marginBottom: '6px' }}>
                  <Cpu size={12} /> MODEL VERSION: {forecastResult.model_version}
                </span>
                <h3 className="font-heading" style={{ fontSize: '1.1rem', color: '#fff', marginTop: '4px' }}>
                  MODEL PERFORMANCE METRICS
                </h3>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <div style={{ background: 'rgba(6, 11, 17, 0.7)', padding: '12px', borderRadius: '8px' }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>MEAN ABSOLUTE ERROR (MAE)</div>
                  <div className="font-mono" style={{ fontSize: '1.2rem', fontWeight: 700, color: '#38bdf8', marginTop: '2px' }}>
                    {forecastResult.metrics.mae} <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>{forecastResult.unit}</span>
                  </div>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-dim)', marginTop: '2px' }}>Average magnitude of errors</div>
                </div>

                <div style={{ background: 'rgba(6, 11, 17, 0.7)', padding: '12px', borderRadius: '8px' }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>ROOT MEAN SQUARED ERROR (RMSE)</div>
                  <div className="font-mono" style={{ fontSize: '1.2rem', fontWeight: 700, color: '#eab308', marginTop: '2px' }}>
                    {forecastResult.metrics.rmse} <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>{forecastResult.unit}</span>
                  </div>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-dim)', marginTop: '2px' }}>Penalizes larger variance errors</div>
                </div>

                <div style={{ background: 'rgba(6, 11, 17, 0.7)', padding: '12px', borderRadius: '8px' }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>MEAN ABSOLUTE PERCENTAGE ERROR</div>
                  <div className="font-mono" style={{ fontSize: '1.2rem', fontWeight: 700, color: '#10b981', marginTop: '2px' }}>
                    {forecastResult.metrics.mape}%
                  </div>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-dim)', marginTop: '2px' }}>Percentage deviation from baseline</div>
                </div>
              </div>

              <div style={{ marginTop: 'auto', fontSize: '0.75rem', color: 'var(--text-dim)', borderTop: '1px solid rgba(255, 255, 255, 0.06)', paddingTop: '10px' }}>
                Note: Evaluated dynamically using cross-validation on historical consumption sequences.
              </div>
            </div>
          </div>
        </>
      ) : null}
    </div>
  );
};

/* =========================================================================
   Interactive SVG Time-Series Forecast Chart Component
   ========================================================================= */
interface ForecastChartProps {
  historicalData: { date: string; quantity: number }[];
  forecastData: { date: string; predicted_quantity: number; lower_bound: number | null; upper_bound: number | null }[];
  unit: string;
  onHover: (point: { date: string; value: number; type: 'hist' | 'pred' } | null) => void;
}

const ForecastChart: React.FC<ForecastChartProps> = ({ historicalData, forecastData, unit, onHover }) => {
  const width = 900;
  const height = 260;
  const padding = { top: 20, right: 30, bottom: 35, left: 50 };

  const allPoints = [
    ...historicalData.map(d => ({ date: d.date, val: d.quantity, type: 'hist' as const })),
    ...forecastData.map(d => ({ date: d.date, val: d.predicted_quantity, type: 'pred' as const }))
  ];

  if (allPoints.length === 0) return null;

  const maxVal = Math.max(
    ...allPoints.map(p => p.val),
    ...forecastData.map(d => d.upper_bound || 0),
    100
  ) * 1.15;

  const chartWidth = width - padding.left - padding.right;
  const chartHeight = height - padding.top - padding.bottom;

  const getX = (index: number) => padding.left + (index / (allPoints.length - 1)) * chartWidth;
  const getY = (val: number) => padding.top + chartHeight - (val / maxVal) * chartHeight;

  const histIndexEnd = historicalData.length - 1;

  // Build SVG Path strings
  const histPointsStr = historicalData
    .map((d, i) => `${getX(i)},${getY(d.quantity)}`)
    .join(' L ');

  const predPointsStr = [
    `${getX(histIndexEnd)},${getY(historicalData[histIndexEnd]?.quantity || forecastData[0]?.predicted_quantity || 0)}`,
    ...forecastData.map((d, i) => `${getX(histIndexEnd + i + 1)},${getY(d.predicted_quantity)}`)
  ].join(' L ');

  // Confidence Bounds Shaded Polygon Area
  const upperBoundsPath = [
    `${getX(histIndexEnd)},${getY(historicalData[histIndexEnd]?.quantity || 0)}`,
    ...forecastData.map((d, i) => `${getX(histIndexEnd + i + 1)},${getY(d.upper_bound || d.predicted_quantity)}`)
  ];

  const lowerBoundsPath = [
    ...forecastData.map((d, i) => `${getX(histIndexEnd + i + 1)},${getY(d.lower_bound || d.predicted_quantity)}`).reverse(),
    `${getX(histIndexEnd)},${getY(historicalData[histIndexEnd]?.quantity || 0)}`
  ];

  const boundsAreaPolygon = [...upperBoundsPath, ...lowerBoundsPath].join(' L ') + ' Z';

  return (
    <div style={{ position: 'relative', width: '100%', overflowX: 'auto' }}>
      <svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}>
        {/* Horizontal Grid lines */}
        {[0, 0.25, 0.5, 0.75, 1.0].map(ratio => {
          const y = padding.top + chartHeight * (1 - ratio);
          const valLabel = Math.round(maxVal * ratio);
          return (
            <g key={ratio}>
              <line x1={padding.left} y1={y} x2={width - padding.right} y2={y} stroke="rgba(255,255,255,0.06)" strokeDasharray="3,3" />
              <text x={padding.left - 8} y={y + 4} textAnchor="end" fill="var(--text-dim)" fontSize="10" fontFamily="JetBrains Mono">
                {valLabel}
              </text>
            </g>
          );
        })}

        {/* Shaded Confidence Band */}
        {forecastData.length > 0 && (
          <path d={`M ${boundsAreaPolygon}`} fill="rgba(234, 179, 8, 0.12)" stroke="none" />
        )}

        {/* Boundary vertical line for Today */}
        {histIndexEnd >= 0 && (
          <g>
            <line
              x1={getX(histIndexEnd)}
              y1={padding.top}
              x2={getX(histIndexEnd)}
              y2={height - padding.bottom}
              stroke="#38bdf8"
              strokeDasharray="4,4"
              strokeWidth="1.5"
            />
            <text x={getX(histIndexEnd)} y={padding.top - 4} textAnchor="middle" fill="#38bdf8" fontSize="10" fontFamily="Rajdhani" fontWeight="bold">
              TODAY BOUNDARY
            </text>
          </g>
        )}

        {/* Historical Line (Solid Cyan) */}
        {historicalData.length > 0 && (
          <path d={`M ${histPointsStr}`} fill="none" stroke="#38bdf8" strokeWidth="2.5" />
        )}

        {/* Forecast Line (Dashed Gold) */}
        {forecastData.length > 0 && (
          <path d={`M ${predPointsStr}`} fill="none" stroke="#eab308" strokeWidth="2.5" strokeDasharray="6,4" />
        )}

        {/* Interactive Dots for Historical Data */}
        {historicalData.map((d, i) => (
          <circle
            key={`h-${i}`}
            cx={getX(i)}
            cy={getY(d.quantity)}
            r="4"
            fill="#0a111a"
            stroke="#38bdf8"
            strokeWidth="2"
            onMouseEnter={() => onHover({ date: d.date, value: d.quantity, type: 'hist' })}
            onMouseLeave={() => onHover(null)}
            style={{ cursor: 'pointer' }}
          />
        ))}

        {/* Interactive Dots for Forecast Data */}
        {forecastData.map((d, i) => {
          const idx = histIndexEnd + i + 1;
          return (
            <circle
              key={`f-${i}`}
              cx={getX(idx)}
              cy={getY(d.predicted_quantity)}
              r="4.5"
              fill="#eab308"
              stroke="#0a111a"
              strokeWidth="1.5"
              onMouseEnter={() => onHover({ date: d.date, value: d.predicted_quantity, type: 'pred' })}
              onMouseLeave={() => onHover(null)}
              style={{ cursor: 'pointer' }}
            />
          );
        })}

        {/* X-Axis Date Labels */}
        {allPoints.map((p, i) => {
          if (i % Math.ceil(allPoints.length / 8) !== 0 && i !== allPoints.length - 1) return null;
          return (
            <text
              key={`x-${i}`}
              x={getX(i)}
              y={height - 10}
              textAnchor="middle"
              fill="var(--text-dim)"
              fontSize="9"
              fontFamily="JetBrains Mono"
            >
              {p.date.slice(5)}
            </text>
          );
        })}
      </svg>
    </div>
  );
};
