import React, { useState, useEffect, useMemo } from 'react';
import {
  Package,
  AlertTriangle,
  CheckCircle2,
  Clock,
  TrendingDown,
  TrendingUp,
  RefreshCw,
  Truck,
  ArrowRight,
  ShieldAlert,
  Info,
  Layers,
  Sliders,
  Filter,
  Search,
  Calendar,
  Compass,
  Zap,
  Target
} from 'lucide-react';
import { Location, InventoryItem, ConsumptionRecord } from '../types/schema';
import { inventoryService } from '../inventory/inventory.service';
import {
  InventoryIntelligenceResult,
  MultiLocationInventoryRow,
  InventoryStatus,
  RiskPriority
} from '../inventory/inventory.types';
import { INVENTORY_CONFIG } from '../inventory/inventory.config';

interface InventoryIntelligenceViewProps {
  locations: Location[];
  inventory: InventoryItem[];
  consumption: ConsumptionRecord[];
  onAutoGenerateDispatch: (destId: string, supplyType: string, quantity: number) => void;
  onReseedDemoData?: () => void;
}

export const InventoryIntelligenceView: React.FC<InventoryIntelligenceViewProps> = ({
  locations,
  inventory,
  consumption,
  onAutoGenerateDispatch,
  onReseedDemoData
}) => {
  // Top Filter States
  const [selectedLocationId, setSelectedLocationId] = useState<string>(
    locations[3]?.location_id || locations[0]?.location_id || 'loc-004' // Default to Siachen Base Camp
  );
  const [selectedSupplyType, setSelectedSupplyType] = useState<string>(
    'Extreme Cold Climate Rations (ECC)'
  );
  const [analysisPeriodDays, setAnalysisPeriodDays] = useState<number>(
    INVENTORY_CONFIG.DEFAULT_ANALYSIS_PERIOD_DAYS
  );
  const [planningHorizonDays, setPlanningHorizonDays] = useState<number>(
    INVENTORY_CONFIG.DEFAULT_PLANNING_HORIZON_DAYS
  );
  const [useForecast, setUseForecast] = useState<boolean>(true);
  const [customLeadTime, setCustomLeadTime] = useState<number | undefined>(undefined);

  // Data Loading & Results
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [intelResult, setIntelResult] = useState<InventoryIntelligenceResult | null>(null);
  const [multiLocationRows, setMultiLocationRows] = useState<MultiLocationInventoryRow[]>([]);
  const [overviewFilterRisk, setOverviewFilterRisk] = useState<string>('ALL');
  const [overviewSearch, setOverviewSearch] = useState<string>('');
  const [hoveredChartPoint, setHoveredChartPoint] = useState<{
    date: string;
    value: number;
    type: 'hist' | 'pred';
  } | null>(null);

  // Available supply types for currently selected location
  const availableSuppliesForLocation = useMemo(() => {
    const matched = inventory.filter(i => i.location_id === selectedLocationId);
    if (matched.length > 0) {
      return Array.from(new Set(matched.map(i => i.supply_type)));
    }
    return Array.from(new Set(inventory.map(i => i.supply_type)));
  }, [inventory, selectedLocationId]);

  // Ensure selectedSupplyType is valid when location changes
  useEffect(() => {
    if (
      availableSuppliesForLocation.length > 0 &&
      !availableSuppliesForLocation.includes(selectedSupplyType)
    ) {
      setSelectedSupplyType(availableSuppliesForLocation[0]);
    }
  }, [availableSuppliesForLocation, selectedSupplyType]);

  // Load Intelligence Data for the selected location + supply
  const loadIntelligence = async () => {
    if (!selectedLocationId || !selectedSupplyType) return;
    setIsLoading(true);
    try {
      const result = await inventoryService.getInventoryIntelligence({
        location_id: selectedLocationId,
        supply_type: selectedSupplyType,
        analysis_period_days: analysisPeriodDays,
        planning_horizon_days: planningHorizonDays,
        custom_lead_time_days: customLeadTime,
        use_forecast: useForecast
      });
      setIntelResult(result);

      // Load multi-location overview
      const overview = await inventoryService.getMultiLocationInventoryOverview(
        analysisPeriodDays,
        planningHorizonDays
      );
      setMultiLocationRows(overview);
    } catch (err) {
      console.error('Failed to calculate inventory intelligence:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadIntelligence();
  }, [
    selectedLocationId,
    selectedSupplyType,
    analysisPeriodDays,
    planningHorizonDays,
    useForecast,
    customLeadTime,
    inventory,
    consumption
  ]);

  // Quick preset scenario loaders for demonstration
  const handleSelectPreset = (locId: string, supply: string) => {
    setSelectedLocationId(locId);
    setSelectedSupplyType(supply);
  };

  // Status Styling Helpers
  const getStatusBadge = (status: InventoryStatus) => {
    switch (status) {
      case 'CRITICAL':
        return {
          bg: '#ef4444',
          color: '#ffffff',
          label: 'CRITICAL',
          icon: AlertTriangle
        };
      case 'HIGH_RISK':
        return {
          bg: '#f97316',
          color: '#ffffff',
          label: 'HIGH RISK',
          icon: AlertTriangle
        };
      case 'AT_RISK':
        return {
          bg: '#eab308',
          color: '#000000',
          label: 'AT RISK',
          icon: AlertTriangle
        };
      case 'HEALTHY':
        return {
          bg: '#10b981',
          color: '#ffffff',
          label: 'HEALTHY',
          icon: CheckCircle2
        };
      case 'INSUFFICIENT_DATA':
      default:
        return {
          bg: '#64748b',
          color: '#ffffff',
          label: 'INSUFFICIENT DATA',
          icon: Info
        };
    }
  };

  // Filtered Multi-Location Overview
  const filteredOverviewRows = multiLocationRows.filter(row => {
    const matchesRisk = overviewFilterRisk === 'ALL' || row.risk_level === overviewFilterRisk;
    const matchesSearch =
      row.location_name.toLowerCase().includes(overviewSearch.toLowerCase()) ||
      row.supply_type.toLowerCase().includes(overviewSearch.toLowerCase()) ||
      row.terrain.toLowerCase().includes(overviewSearch.toLowerCase());
    return matchesRisk && matchesSearch;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '22px' }}>
      {/* Top Banner */}
      <div
        className="glass-panel"
        style={{
          padding: '22px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '16px',
          borderLeft: '4px solid #eab308'
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
          <div
            style={{
              width: '46px',
              height: '46px',
              borderRadius: '10px',
              background: 'linear-gradient(135deg, rgba(234, 179, 8, 0.25), rgba(16, 185, 129, 0.15))',
              border: '1px solid rgba(234, 179, 8, 0.5)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
          >
            <Layers size={24} color="#eab308" />
          </div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <h2
                className="font-heading"
                style={{ fontSize: '1.5rem', color: '#fff', letterSpacing: '0.05em' }}
              >
                MODULE 2 — INVENTORY INTELLIGENCE & REORDER OPTIMIZER
              </h2>
              <span className="badge badge-warning" style={{ fontSize: '0.7rem' }}>
                PS ID: 26251
              </span>
            </div>
            <p style={{ fontSize: '0.84rem', color: 'var(--text-muted)', marginTop: '4px' }}>
              Deterministic supply runway estimation, lead-time reorder thresholds, safety stock modeling, and predictive stockout alerts.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {onReseedDemoData && (
            <button
              onClick={onReseedDemoData}
              className="btn-secondary"
              style={{ fontSize: '0.82rem', padding: '8px 14px' }}
              title="Reseed 180-day simulated dataset for testing and verification"
            >
              <RefreshCw size={14} /> RESEED 180-DAY DEMO DATA
            </button>
          )}
          <button
            onClick={loadIntelligence}
            disabled={isLoading}
            className="btn-primary"
            style={{ fontSize: '0.82rem', padding: '8px 16px' }}
          >
            <RefreshCw size={14} className={isLoading ? 'animate-spin' : ''} /> RECALCULATE
          </button>
        </div>
      </div>

      {/* Benchmark Scenario Quick Buttons (Section 32 & 33) */}
      <div
        className="glass-panel"
        style={{
          padding: '12px 18px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          overflowX: 'auto',
          fontSize: '0.82rem'
        }}
      >
        <span style={{ color: 'var(--text-muted)', fontWeight: 600, whiteSpace: 'nowrap' }}>
          QUICK SCENARIOS:
        </span>
        <button
          onClick={() => handleSelectPreset('loc-004', 'Extreme Cold Climate Rations (ECC)')}
          style={{
            padding: '5px 12px',
            borderRadius: '6px',
            border: '1px solid rgba(239, 68, 68, 0.4)',
            background: 'rgba(239, 68, 68, 0.1)',
            color: '#f87171',
            cursor: 'pointer',
            whiteSpace: 'nowrap',
            fontWeight: 600
          }}
        >
          🚨 Siachen Rations (Critical Deficit, &lt; 2 Days)
        </button>
        <button
          onClick={() => handleSelectPreset('loc-005', 'High-Altitude Special Clothing (ECC Clothing)')}
          style={{
            padding: '5px 12px',
            borderRadius: '6px',
            border: '1px solid rgba(234, 179, 8, 0.4)',
            background: 'rgba(234, 179, 8, 0.1)',
            color: '#facc15',
            cursor: 'pointer',
            whiteSpace: 'nowrap',
            fontWeight: 600
          }}
        >
          ⚠️ DBO Outpost Clothing (At Risk, 4.8 Days)
        </button>
        <button
          onClick={() => handleSelectPreset('loc-002', 'Ammunition 155mm Artillery')}
          style={{
            padding: '5px 12px',
            borderRadius: '6px',
            border: '1px solid rgba(16, 185, 129, 0.4)',
            background: 'rgba(16, 185, 129, 0.1)',
            color: '#34d399',
            cursor: 'pointer',
            whiteSpace: 'nowrap',
            fontWeight: 600
          }}
        >
          ✅ Leh HQ Artillery (Healthy Buffer, 20+ Days)
        </button>
        <button
          onClick={() => handleSelectPreset('loc-005', 'Diesel Winter Grade (-30C)')}
          style={{
            padding: '5px 12px',
            borderRadius: '6px',
            border: '1px solid rgba(249, 115, 22, 0.4)',
            background: 'rgba(249, 115, 22, 0.1)',
            color: '#fb923c',
            cursor: 'pointer',
            whiteSpace: 'nowrap',
            fontWeight: 600
          }}
        >
          ⚡ DBO Diesel (-30C) (Reorder Breached)
        </button>
      </div>

      {/* TOP FILTERS (Section 18) */}
      <div
        className="glass-panel military-grid-pattern"
        style={{
          padding: '20px',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))',
          gap: '16px',
          alignItems: 'end'
        }}
      >
        {/* 1. Location Selector */}
        <div>
          <label
            className="font-heading"
            style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}
          >
            LOCATION (`location_id`)
          </label>
          <select
            value={selectedLocationId}
            onChange={e => setSelectedLocationId(e.target.value)}
            className="input-field font-heading"
            style={{ fontWeight: 600, width: '100%' }}
          >
            {locations.map(loc => (
              <option key={loc.location_id} value={loc.location_id}>
                {loc.name} ({loc.terrain})
              </option>
            ))}
          </select>
        </div>

        {/* 2. Supply Selector */}
        <div>
          <label
            className="font-heading"
            style={{ fontSize: '0.82rem', color: '#eab308', display: 'block', marginBottom: '6px' }}
          >
            SUPPLY ITEM (`supply_type`)
          </label>
          <select
            value={selectedSupplyType}
            onChange={e => setSelectedSupplyType(e.target.value)}
            className="input-field font-heading"
            style={{ fontWeight: 600, width: '100%' }}
          >
            {availableSuppliesForLocation.map(st => (
              <option key={st} value={st}>
                {st}
              </option>
            ))}
          </select>
        </div>

        {/* 3. Analysis Period Selector */}
        <div>
          <label
            className="font-heading"
            style={{ fontSize: '0.82rem', color: '#38bdf8', display: 'block', marginBottom: '6px' }}
          >
            ANALYSIS PERIOD (HISTORICAL)
          </label>
          <select
            value={analysisPeriodDays}
            onChange={e => setAnalysisPeriodDays(Number(e.target.value))}
            className="input-field font-mono"
            style={{ width: '100%' }}
          >
            {INVENTORY_CONFIG.ANALYSIS_PERIODS.map(p => (
              <option key={p} value={p}>
                Last {p} Days {p === 30 ? '(Default)' : ''}
              </option>
            ))}
          </select>
        </div>

        {/* 4. Planning Horizon Selector */}
        <div>
          <label
            className="font-heading"
            style={{ fontSize: '0.82rem', color: '#38bdf8', display: 'block', marginBottom: '6px' }}
          >
            PLANNING HORIZON (FORWARD)
          </label>
          <select
            value={planningHorizonDays}
            onChange={e => setPlanningHorizonDays(Number(e.target.value))}
            className="input-field font-mono"
            style={{ width: '100%' }}
          >
            {INVENTORY_CONFIG.PLANNING_HORIZONS.map(h => (
              <option key={h} value={h}>
                Next {h} Days {h === 7 ? '(Default)' : ''}
              </option>
            ))}
          </select>
        </div>

        {/* 5. Demand Basis Mode Toggle (Section 13) */}
        <div>
          <label
            className="font-heading"
            style={{ fontSize: '0.82rem', color: '#a855f7', display: 'block', marginBottom: '6px' }}
          >
            DEMAND ESTIMATION BASIS
          </label>
          <button
            onClick={() => setUseForecast(!useForecast)}
            className="input-field"
            style={{
              width: '100%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              cursor: 'pointer',
              background: useForecast ? 'rgba(168, 85, 247, 0.15)' : 'rgba(15, 23, 36, 0.6)',
              borderColor: useForecast ? '#a855f7' : 'rgba(255, 255, 255, 0.1)'
            }}
          >
            <span style={{ fontSize: '0.82rem', fontWeight: 600, color: useForecast ? '#c084fc' : '#9ca3af' }}>
              {useForecast ? 'MODE A: AI FORECAST' : 'MODE B: HISTORICAL AVG'}
            </span>
            <span
              className={`badge ${useForecast ? 'badge-info' : 'badge-secondary'}`}
              style={{ fontSize: '0.65rem' }}
            >
              {useForecast ? 'ACTIVE' : 'FALLBACK'}
            </span>
          </button>
        </div>
      </div>

      {isLoading && (
        <div className="glass-panel" style={{ padding: '40px', textAlign: 'center' }}>
          <RefreshCw size={28} className="animate-spin" color="#eab308" style={{ margin: '0 auto 12px auto' }} />
          <p style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-heading)', letterSpacing: '0.05em' }}>
            EXECUTING INVENTORY INTELLIGENCE PIPELINE FOR {selectedSupplyType.toUpperCase()}...
          </p>
        </div>
      )}

      {!isLoading && intelResult && (
        <>
          {/* PROMINENT INVENTORY STATUS CARD (Section 20) */}
          <div
            className="glass-panel"
            style={{
              padding: '24px',
              border: `2px solid ${
                intelResult.status === 'CRITICAL'
                  ? '#ef4444'
                  : intelResult.status === 'HIGH_RISK'
                  ? '#f97316'
                  : intelResult.status === 'AT_RISK'
                  ? '#eab308'
                  : '#10b981'
              }`,
              background:
                intelResult.status === 'CRITICAL'
                  ? 'radial-gradient(circle at 10% 20%, rgba(239, 68, 68, 0.15), rgba(15, 23, 36, 0.8))'
                  : intelResult.status === 'HIGH_RISK'
                  ? 'radial-gradient(circle at 10% 20%, rgba(249, 115, 22, 0.15), rgba(15, 23, 36, 0.8))'
                  : 'radial-gradient(circle at 10% 20%, rgba(234, 179, 8, 0.12), rgba(15, 23, 36, 0.8))'
            }}
          >
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                flexWrap: 'wrap',
                gap: '16px',
                borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
                paddingBottom: '16px',
                marginBottom: '18px'
              }}
            >
              <div>
                <span style={{ fontSize: '0.78rem', color: '#eab308', letterSpacing: '0.08em', fontWeight: 700 }} className="font-heading">
                  OPERATIONAL THEATER INVENTORY STATUS
                </span>
                <h3 className="font-heading" style={{ fontSize: '1.6rem', color: '#fff', marginTop: '2px' }}>
                  {intelResult.location_name} — <span style={{ color: '#eab308' }}>{intelResult.supply_type}</span>
                </h3>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>DEMAND BASIS</div>
                  <span
                    className={`badge ${intelResult.demand_basis === 'FORECAST' ? 'badge-info' : 'badge-secondary'}`}
                    style={{ fontSize: '0.75rem', marginTop: '2px' }}
                  >
                    {intelResult.demand_basis === 'FORECAST' ? 'AI FORECAST' : 'HISTORICAL AVERAGE'}
                  </span>
                </div>

                <div
                  style={{
                    padding: '8px 18px',
                    borderRadius: '8px',
                    background: getStatusBadge(intelResult.status).bg,
                    color: getStatusBadge(intelResult.status).color,
                    fontWeight: 700,
                    fontSize: '1rem',
                    fontFamily: 'var(--font-heading)',
                    letterSpacing: '0.06em',
                    boxShadow: '0 4px 14px rgba(0,0,0,0.4)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px'
                  }}
                >
                  <AlertTriangle size={18} />
                  {getStatusBadge(intelResult.status).label}
                </div>
              </div>
            </div>

            {/* Quick Metrics Inside Prominent Status Banner */}
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                gap: '16px'
              }}
            >
              <div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>CURRENT INVENTORY</div>
                <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#fff' }}>
                  {intelResult.current_inventory.toLocaleString()} <span style={{ fontSize: '0.9rem', color: 'var(--text-dim)' }}>{intelResult.unit}</span>
                </div>
              </div>

              <div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>DAYS OF SUPPLY</div>
                <div
                  className="font-mono font-heading"
                  style={{
                    fontSize: '1.8rem',
                    fontWeight: 700,
                    color:
                      intelResult.days_of_supply === null
                        ? '#9ca3af'
                        : intelResult.days_of_supply < 2
                        ? '#ef4444'
                        : intelResult.days_of_supply < 4
                        ? '#f97316'
                        : intelResult.days_of_supply <= 7
                        ? '#eab308'
                        : '#10b981'
                  }}
                >
                  {intelResult.days_of_supply_display}
                </div>
              </div>

              <div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>REORDER STATUS</div>
                <div style={{ marginTop: '4px' }}>
                  {intelResult.reorder_required ? (
                    <span className="badge badge-danger" style={{ fontSize: '0.85rem', padding: '6px 12px' }}>
                      <AlertTriangle size={14} /> REORDER REQUIRED
                    </span>
                  ) : (
                    <span className="badge badge-success" style={{ fontSize: '0.85rem', padding: '6px 12px' }}>
                      <CheckCircle2 size={14} /> NO IMMEDIATE REORDER
                    </span>
                  )}
                </div>
              </div>

              <div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>PROJECTED STOCKOUT</div>
                <div className="font-mono" style={{ fontSize: '0.95rem', fontWeight: 600, color: '#f3f4f6', marginTop: '6px' }}>
                  {intelResult.stockout_day_index !== null ? `During Day ${intelResult.stockout_day_index}` : 'No Stockout'}
                </div>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>
                  {intelResult.projected_stockout_date ? `Est: ${intelResult.projected_stockout_date}` : 'Stable runway'}
                </div>
              </div>
            </div>
          </div>

          {/* 6 KPI CARDS (Section 19) */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
              gap: '16px'
            }}
          >
            {/* KPI 1: Current Inventory */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>CURRENT INVENTORY</span>
                <Package size={18} color="#eab308" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#fff', marginTop: '6px' }}>
                {intelResult.current_inventory.toLocaleString()}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                {intelResult.unit} on hand at base
              </div>
            </div>

            {/* KPI 2: Avg Daily Consumption */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>AVG DAILY CONSUMPTION</span>
                <TrendingDown size={18} color="#38bdf8" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#38bdf8', marginTop: '6px' }}>
                {intelResult.average_daily_consumption !== null
                  ? `${intelResult.average_daily_consumption.toFixed(INVENTORY_CONFIG.DECIMAL_PRECISION.AVG_DAILY_CONSUMPTION)}`
                  : 'N/A'}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                {intelResult.unit}/day (Last {intelResult.analysis_period_days} days)
              </div>
            </div>

            {/* KPI 3: Days of Supply */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>DAYS OF SUPPLY</span>
                <Clock size={18} color="#a855f7" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#c084fc', marginTop: '6px' }}>
                {intelResult.days_of_supply_display}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                Inventory / Avg Daily Burn
              </div>
            </div>

            {/* KPI 4: Reorder Point */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>REORDER POINT (ROP)</span>
                <Target size={18} color="#f97316" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#f97316', marginTop: '6px' }}>
                {intelResult.reorder_point !== null ? intelResult.reorder_point.toLocaleString() : 'N/A'}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                Lead Demand + Safety Stock
              </div>
            </div>

            {/* KPI 5: Projected Shortage */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>PROJECTED SHORTAGE</span>
                <AlertTriangle size={18} color={intelResult.projected_shortage > 0 ? '#ef4444' : '#10b981'} />
              </div>
              <div
                className="font-mono font-heading"
                style={{
                  fontSize: '1.8rem',
                  fontWeight: 700,
                  color: intelResult.projected_shortage > 0 ? '#ef4444' : '#10b981',
                  marginTop: '6px'
                }}
              >
                {intelResult.projected_shortage.toLocaleString()}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                {intelResult.projected_shortage > 0 ? `Deficit over next ${intelResult.planning_horizon_days}d` : 'Zero shortage projected'}
              </div>
            </div>

            {/* KPI 6: Recommended Reorder */}
            <div className="glass-panel" style={{ padding: '18px 20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: 600 }}>RECOMMENDED REORDER</span>
                <Truck size={18} color="#eab308" />
              </div>
              <div className="font-mono font-heading" style={{ fontSize: '1.8rem', fontWeight: 700, color: '#eab308', marginTop: '6px' }}>
                {intelResult.recommended_reorder_quantity.toLocaleString()}
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--text-dim)', marginTop: '4px' }}>
                {intelResult.unit} (Target stock - Current)
              </div>
            </div>
          </div>

          {/* INVENTORY LEVEL VISUALIZATION (Section 21) & REORDER POINT VISUALIZATION (Section 23) */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))', gap: '20px' }}>
            {/* Inventory Level Visual Bar */}
            <div className="glass-panel" style={{ padding: '20px' }}>
              <h3 className="font-heading" style={{ fontSize: '1.15rem', color: '#fff', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Sliders size={18} color="#eab308" /> STOCK LEVEL VISUALIZATION & RUNWAY GAUGE
              </h3>

              <div style={{ marginBottom: '18px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '8px' }}>
                  <span>
                    Current Stock:{' '}
                    <strong style={{ color: '#fff' }} className="font-mono">
                      {intelResult.current_inventory.toLocaleString()} {intelResult.unit}
                    </strong>
                  </span>
                  <span>
                    Target Stock:{' '}
                    <strong style={{ color: '#eab308' }} className="font-mono">
                      {intelResult.target_stock_level !== null ? intelResult.target_stock_level.toLocaleString() : 'N/A'}{' '}
                      {intelResult.unit}
                    </strong>
                  </span>
                </div>

                {/* Multi-layered progress bar */}
                {(() => {
                  const maxRef = Math.max(
                    intelResult.target_stock_level || 1,
                    intelResult.current_inventory,
                    (intelResult.reorder_point || 0) * 1.2,
                    100
                  );
                  const currentPct = Math.min(100, (intelResult.current_inventory / maxRef) * 100);
                  const ropPct = intelResult.reorder_point ? Math.min(100, (intelResult.reorder_point / maxRef) * 100) : 0;
                  const safetyPct = Math.min(100, (intelResult.safety_stock / maxRef) * 100);

                  return (
                    <div style={{ position: 'relative', margin: '24px 0' }}>
                      {/* Bar background */}
                      <div
                        style={{
                          height: '24px',
                          background: 'rgba(255, 255, 255, 0.08)',
                          borderRadius: '12px',
                          position: 'relative',
                          overflow: 'hidden'
                        }}
                      >
                        {/* Safety Stock buffer band */}
                        <div
                          style={{
                            position: 'absolute',
                            left: 0,
                            top: 0,
                            bottom: 0,
                            width: `${safetyPct}%`,
                            background: 'rgba(239, 68, 68, 0.25)',
                            borderRight: '1px dashed rgba(239, 68, 68, 0.5)'
                          }}
                          title="Safety Stock Buffer"
                        />

                        {/* Current Inventory Fill */}
                        <div
                          style={{
                            height: '100%',
                            width: `${currentPct}%`,
                            background:
                              intelResult.status === 'CRITICAL'
                                ? 'linear-gradient(90deg, #ef4444, #f87171)'
                                : intelResult.status === 'HIGH_RISK'
                                ? 'linear-gradient(90deg, #f97316, #fb923c)'
                                : intelResult.status === 'AT_RISK'
                                ? 'linear-gradient(90deg, #eab308, #fde047)'
                                : 'linear-gradient(90deg, #10b981, #34d399)',
                            borderRadius: '12px',
                            transition: 'width 0.4s ease'
                          }}
                        />
                      </div>

                      {/* Reorder Point Vertical Marker */}
                      {ropPct > 0 && (
                        <div
                          style={{
                            position: 'absolute',
                            left: `${ropPct}%`,
                            top: '-8px',
                            bottom: '-8px',
                            width: '2px',
                            background: '#f97316',
                            transform: 'translateX(-50%)',
                            zIndex: 10
                          }}
                        >
                          <div
                            style={{
                              position: 'absolute',
                              top: '-20px',
                              left: '50%',
                              transform: 'translateX(-50%)',
                              fontSize: '0.68rem',
                              color: '#f97316',
                              fontWeight: 700,
                              whiteSpace: 'nowrap',
                              background: 'rgba(10, 17, 26, 0.95)',
                              padding: '1px 5px',
                              borderRadius: '3px',
                              border: '1px solid #f97316'
                            }}
                          >
                            ROP: {intelResult.reorder_point}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })()}

                {/* Legend */}
                <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', fontSize: '0.76rem', color: 'var(--text-muted)' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: '#10b981' }} /> Current Stock
                  </span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: '#f97316' }} /> Reorder Point (ROP)
                  </span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: 'rgba(239, 68, 68, 0.4)' }} /> Safety Reserve
                  </span>
                </div>
              </div>

              {/* Status details line */}
              <div style={{ padding: '12px', background: 'rgba(6, 11, 17, 0.6)', borderRadius: '8px', fontSize: '0.82rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Lead Time Transit:</span>
                  <span style={{ color: '#fff', fontWeight: 600 }} className="font-mono">
                    {intelResult.lead_time_days} Days ({intelResult.lead_time_source})
                  </span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Risk Diagnostic:</span>
                  <span style={{ color: '#f3f4f6' }}>{intelResult.risk_reasoning}</span>
                </div>
              </div>
            </div>

            {/* Reorder Point Breakdown (Section 23) */}
            <div className="glass-panel" style={{ padding: '20px' }}>
              <h3 className="font-heading" style={{ fontSize: '1.15rem', color: '#fff', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Target size={18} color="#f97316" /> REORDER POINT BREAKDOWN & FORMULA
              </h3>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '0.86rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: 'rgba(255, 255, 255, 0.03)', borderRadius: '6px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Current Inventory:</span>
                  <span className="font-mono" style={{ fontWeight: 700, color: '#fff' }}>
                    {intelResult.current_inventory.toLocaleString()} {intelResult.unit}
                  </span>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: 'rgba(255, 255, 255, 0.03)', borderRadius: '6px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>
                    Expected Lead-Time Demand ({intelResult.lead_time_days}d × {intelResult.average_daily_consumption?.toFixed(1) || 0}/d):
                  </span>
                  <span className="font-mono" style={{ fontWeight: 600, color: '#38bdf8' }}>
                    {intelResult.expected_lead_time_demand !== null ? Math.round(intelResult.expected_lead_time_demand).toLocaleString() : 'N/A'}{' '}
                    {intelResult.unit}
                  </span>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: 'rgba(255, 255, 255, 0.03)', borderRadius: '6px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>
                    Safety Stock ({intelResult.safety_stock_method}):
                  </span>
                  <span className="font-mono" style={{ fontWeight: 600, color: '#f87171' }}>
                    {intelResult.safety_stock.toLocaleString()} {intelResult.unit}
                  </span>
                </div>

                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    padding: '10px 12px',
                    background: 'rgba(249, 115, 22, 0.1)',
                    border: '1px solid rgba(249, 115, 22, 0.3)',
                    borderRadius: '6px'
                  }}
                >
                  <span style={{ color: '#f97316', fontWeight: 700 }}>
                    Reorder Point = Lead Demand + Safety Stock:
                  </span>
                  <span className="font-mono" style={{ fontWeight: 700, color: '#f97316', fontSize: '1rem' }}>
                    {intelResult.reorder_point !== null ? intelResult.reorder_point.toLocaleString() : 'N/A'}{' '}
                    {intelResult.unit}
                  </span>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: 'rgba(255, 255, 255, 0.03)', borderRadius: '6px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>
                    Target Stock ({intelResult.planning_horizon_days}d Horizon Demand + Safety):
                  </span>
                  <span className="font-mono" style={{ fontWeight: 600, color: '#eab308' }}>
                    {intelResult.target_stock_level !== null ? intelResult.target_stock_level.toLocaleString() : 'N/A'}{' '}
                    {intelResult.unit}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* HISTORICAL CONSUMPTION & FORECAST TREND CHART (Section 22) */}
          <div className="glass-panel military-grid-pattern" style={{ padding: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <h3 className="font-heading" style={{ fontSize: '1.2rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <TrendingUp size={18} color="#eab308" /> CONSUMPTION TREND & PLANNING HORIZON TRAJECTORY
                </h3>
                <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '2px' }}>
                  Cyan: Historical daily consumption (Last {intelResult.analysis_period_days} days) | Dashed Yellow: Average burn rate | Gold: {intelResult.demand_basis === 'FORECAST' ? 'AI Demand Forecast' : 'Projected demand'}
                </p>
              </div>

              <div style={{ display: 'flex', gap: '14px', fontSize: '0.78rem' }} className="font-mono">
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#38bdf8' }}>
                  <span style={{ width: '12px', height: '3px', background: '#38bdf8' }} /> Actual Consumption
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#facc15' }}>
                  <span style={{ width: '12px', height: '2px', borderTop: '2px dashed #facc15' }} /> Avg Burn Rate
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#eab308' }}>
                  <span style={{ width: '12px', height: '3px', borderTop: '2px dashed #eab308' }} /> Planning Trajectory
                </span>
              </div>
            </div>

            {/* SVG Chart */}
            <div style={{ position: 'relative', width: '100%', overflowX: 'auto' }}>
              {(() => {
                const width = 960;
                const height = 260;
                const padding = { top: 20, right: 30, bottom: 35, left: 50 };

                const histPoints = intelResult.historical_series.slice(-30);
                const forecastPoints = intelResult.forecast_series;

                const allPoints = [
                  ...histPoints.map(p => ({ date: p.date, val: p.quantity, type: 'hist' as const })),
                  ...forecastPoints.map(p => ({ date: p.date, val: p.predicted_quantity, type: 'pred' as const }))
                ];

                if (allPoints.length === 0) {
                  return (
                    <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-dim)' }}>
                      Insufficient consumption records available to plot curve.
                    </div>
                  );
                }

                const maxVal = Math.max(...allPoints.map(p => p.val), 50) * 1.15;
                const chartWidth = width - padding.left - padding.right;
                const chartHeight = height - padding.top - padding.bottom;

                const getX = (index: number) =>
                  padding.left + (index / Math.max(1, allPoints.length - 1)) * chartWidth;
                const getY = (val: number) =>
                  padding.top + chartHeight - (val / maxVal) * chartHeight;

                const histIndexEnd = histPoints.length - 1;

                const histPointsStr = histPoints
                  .map((d, i) => `${getX(i)},${getY(d.quantity)}`)
                  .join(' L ');

                const predPointsStr = [
                  `${getX(histIndexEnd)},${getY(histPoints[histIndexEnd]?.quantity || forecastPoints[0]?.predicted_quantity || 0)}`,
                  ...forecastPoints.map((d, i) => `${getX(histIndexEnd + i + 1)},${getY(d.predicted_quantity)}`)
                ].join(' L ');

                const avgY = intelResult.average_daily_consumption ? getY(intelResult.average_daily_consumption) : null;

                return (
                  <svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}>
                    {/* Horizontal Grid lines */}
                    {[0, 0.25, 0.5, 0.75, 1.0].map(ratio => {
                      const y = padding.top + chartHeight * (1 - ratio);
                      const valLabel = Math.round(maxVal * ratio);
                      return (
                        <g key={ratio}>
                          <line
                            x1={padding.left}
                            y1={y}
                            x2={width - padding.right}
                            y2={y}
                            stroke="rgba(255,255,255,0.06)"
                            strokeDasharray="3,3"
                          />
                          <text
                            x={padding.left - 8}
                            y={y + 4}
                            textAnchor="end"
                            fill="var(--text-dim)"
                            fontSize="10"
                            fontFamily="JetBrains Mono"
                          >
                            {valLabel}
                          </text>
                        </g>
                      );
                    })}

                    {/* Average Daily Consumption Reference Line */}
                    {avgY !== null && (
                      <g>
                        <line
                          x1={padding.left}
                          y1={avgY}
                          x2={width - padding.right}
                          y2={avgY}
                          stroke="#facc15"
                          strokeDasharray="6,4"
                          strokeWidth="1.5"
                        />
                        <text
                          x={width - padding.right}
                          y={avgY - 6}
                          textAnchor="end"
                          fill="#facc15"
                          fontSize="10"
                          fontFamily="JetBrains Mono"
                        >
                          Avg: {intelResult.average_daily_consumption?.toFixed(1)} {intelResult.unit}/day
                        </text>
                      </g>
                    )}

                    {/* Historical Actual Line */}
                    {histPoints.length > 0 && (
                      <path
                        d={`M ${histPointsStr}`}
                        fill="none"
                        stroke="#38bdf8"
                        strokeWidth="2.5"
                        strokeLinecap="round"
                      />
                    )}

                    {/* Historical Data Circles */}
                    {histPoints.map((d, i) => (
                      <circle
                        key={d.date}
                        cx={getX(i)}
                        cy={getY(d.quantity)}
                        r="3.5"
                        fill="#38bdf8"
                        stroke="rgba(6, 11, 17, 0.8)"
                        strokeWidth="1.5"
                        style={{ cursor: 'pointer' }}
                        onMouseEnter={() => setHoveredChartPoint({ date: d.date, value: d.quantity, type: 'hist' })}
                        onMouseLeave={() => setHoveredChartPoint(null)}
                      />
                    ))}

                    {/* Forecast Future Line */}
                    {forecastPoints.length > 0 && histIndexEnd >= 0 && (
                      <path
                        d={`M ${predPointsStr}`}
                        fill="none"
                        stroke="#eab308"
                        strokeWidth="2.5"
                        strokeDasharray="5,4"
                        strokeLinecap="round"
                      />
                    )}

                    {/* Forecast Data Circles */}
                    {forecastPoints.map((d, i) => (
                      <circle
                        key={d.date}
                        cx={getX(histIndexEnd + i + 1)}
                        cy={getY(d.predicted_quantity)}
                        r="4"
                        fill="#eab308"
                        stroke="rgba(6, 11, 17, 0.8)"
                        strokeWidth="1.5"
                        style={{ cursor: 'pointer' }}
                        onMouseEnter={() => setHoveredChartPoint({ date: d.date, value: d.predicted_quantity, type: 'pred' })}
                        onMouseLeave={() => setHoveredChartPoint(null)}
                      />
                    ))}

                    {/* Today Partition Line */}
                    {histIndexEnd >= 0 && (
                      <g>
                        <line
                          x1={getX(histIndexEnd)}
                          y1={padding.top}
                          x2={getX(histIndexEnd)}
                          y2={height - padding.bottom}
                          stroke="#ef4444"
                          strokeDasharray="4,4"
                          strokeWidth="1.5"
                        />
                        <text
                          x={getX(histIndexEnd)}
                          y={padding.top - 6}
                          textAnchor="middle"
                          fill="#ef4444"
                          fontSize="10"
                          fontFamily="JetBrains Mono"
                          fontWeight="700"
                        >
                          TODAY
                        </text>
                      </g>
                    )}
                  </svg>
                );
              })()}

              {/* Hover Tooltip display */}
              {hoveredChartPoint && (
                <div
                  style={{
                    marginTop: '8px',
                    padding: '8px 14px',
                    background: 'rgba(10, 17, 26, 0.95)',
                    border: '1px solid #eab308',
                    borderRadius: '6px',
                    display: 'inline-flex',
                    gap: '14px',
                    fontSize: '0.82rem'
                  }}
                >
                  <span>
                    Date: <strong style={{ color: '#fff' }}>{hoveredChartPoint.date}</strong>
                  </span>
                  <span>
                    Type:{' '}
                    <strong style={{ color: hoveredChartPoint.type === 'hist' ? '#38bdf8' : '#eab308' }}>
                      {hoveredChartPoint.type === 'hist' ? 'Historical Consumption' : 'Projected Demand'}
                    </strong>
                  </span>
                  <span>
                    Quantity:{' '}
                    <strong style={{ color: '#fff' }}>
                      {hoveredChartPoint.value.toLocaleString()} {intelResult.unit}
                    </strong>
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* DYNAMIC INVENTORY INSIGHT (Section 24) & RECOMMENDED ACTION (Section 25) */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))', gap: '20px' }}>
            {/* Dynamic Insight Card */}
            <div
              className="glass-panel"
              style={{
                padding: '22px',
                borderLeft: intelResult.projected_shortage > 0 ? '4px solid #ef4444' : '4px solid #10b981'
              }}
            >
              <h3 className="font-heading" style={{ fontSize: '1.2rem', color: '#eab308', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Info size={18} color="#eab308" /> DYNAMIC INVENTORY INTELLIGENCE INSIGHT
              </h3>
              <p style={{ fontSize: '0.94rem', color: '#f3f4f6', lineHeight: 1.6 }}>
                {intelResult.insight_summary}
              </p>
              <div style={{ marginTop: '14px', fontSize: '0.78rem', color: 'var(--text-dim)' }} className="font-mono">
                {intelResult.stockout_projection_narrative}
              </div>
            </div>

            {/* Recommended Action Card (Decision-Support) */}
            <div
              className="glass-panel"
              style={{
                padding: '22px',
                borderLeft: intelResult.recommended_action.priority === 'CRITICAL' ? '4px solid #ef4444' : '4px solid #eab308'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px' }}>
                <div>
                  <h3 className="font-heading" style={{ fontSize: '1.2rem', color: '#fff', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Truck size={18} color="#eab308" /> RECOMMENDED LOGISTICS ACTION
                  </h3>
                  <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#eab308' }} className="font-heading">
                    {intelResult.recommended_action.action}
                  </div>
                  {intelResult.recommended_action.quantity > 0 && (
                    <div style={{ marginTop: '4px', fontSize: '0.92rem' }}>
                      Recommended Reorder Volume:{' '}
                      <strong style={{ color: '#fff' }} className="font-mono">
                        {intelResult.recommended_action.quantity.toLocaleString()} {intelResult.unit}
                      </strong>
                    </div>
                  )}
                  <p style={{ fontSize: '0.84rem', color: 'var(--text-muted)', marginTop: '8px', lineHeight: 1.4 }}>
                    Reason: {intelResult.recommended_action.reason}
                  </p>
                </div>

                {intelResult.recommended_action.quantity > 0 && (
                  <button
                    onClick={() =>
                      onAutoGenerateDispatch(
                        intelResult.location_id,
                        intelResult.supply_type,
                        intelResult.recommended_action.quantity
                      )
                    }
                    className="btn-primary"
                    style={{ fontSize: '0.85rem' }}
                  >
                    <Zap size={14} /> AUTHORIZE DISPATCH
                  </button>
                )}
              </div>

              <div
                style={{
                  marginTop: '14px',
                  padding: '8px 12px',
                  background: 'rgba(255, 255, 255, 0.03)',
                  borderRadius: '6px',
                  fontSize: '0.72rem',
                  color: 'var(--text-dim)',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <ShieldAlert size={14} color="#f97316" />
                Decision-support recommendation only. Convoys are not automatically executed.
              </div>
            </div>
          </div>
        </>
      )}

      {/* MULTI-LOCATION INVENTORY OVERVIEW TABLE (Section 26) */}
      <div className="glass-panel" style={{ overflow: 'hidden' }}>
        <div
          style={{
            padding: '18px 22px',
            borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: '14px'
          }}
        >
          <div>
            <h3 className="font-heading" style={{ fontSize: '1.25rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Compass size={20} color="#eab308" /> THEATER-WIDE MULTI-LOCATION INVENTORY OVERVIEW
            </h3>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '2px' }}>
              Real-time monitoring across all operating bases, forward depots, and supply hubs in the Northern & Eastern Commands.
            </p>
          </div>

          {/* Table Filters */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
            <div style={{ position: 'relative', width: '220px' }}>
              <Search
                size={14}
                color="var(--text-muted)"
                style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)' }}
              />
              <input
                type="text"
                placeholder="Search base or supply..."
                value={overviewSearch}
                onChange={e => setOverviewSearch(e.target.value)}
                className="input-field"
                style={{ paddingLeft: '32px', fontSize: '0.82rem' }}
              />
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Filter size={14} color="var(--text-muted)" />
              <select
                value={overviewFilterRisk}
                onChange={e => setOverviewFilterRisk(e.target.value)}
                className="input-field"
                style={{ fontSize: '0.82rem', width: '150px' }}
              >
                <option value="ALL">All Risk Levels</option>
                <option value="CRITICAL">Critical Only</option>
                <option value="HIGH">High Risk</option>
                <option value="MEDIUM">Medium / At Risk</option>
                <option value="LOW">Healthy / Low Risk</option>
              </select>
            </div>
          </div>
        </div>

        {/* Table */}
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.88rem' }}>
            <thead>
              <tr
                style={{
                  background: 'rgba(6, 11, 17, 0.8)',
                  borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
                  color: '#9ca3af',
                  fontFamily: 'var(--font-heading)',
                  letterSpacing: '0.05em'
                }}
              >
                <th style={{ padding: '12px 16px' }}>OPERATING BASE</th>
                <th style={{ padding: '12px 16px' }}>SUPPLY TYPE</th>
                <th style={{ padding: '12px 16px' }}>AVAILABLE STOCK</th>
                <th style={{ padding: '12px 16px' }}>AVG BURN</th>
                <th style={{ padding: '12px 16px' }}>DAYS OF SUPPLY</th>
                <th style={{ padding: '12px 16px' }}>ROP</th>
                <th style={{ padding: '12px 16px' }}>STATUS & RISK</th>
                <th style={{ padding: '12px 16px', textAlign: 'center' }}>ACTION</th>
              </tr>
            </thead>
            <tbody>
              {filteredOverviewRows.length === 0 ? (
                <tr>
                  <td colSpan={8} style={{ padding: '24px', textAlign: 'center', color: 'var(--text-dim)' }}>
                    No matching inventory records found for current filters.
                  </td>
                </tr>
              ) : (
                filteredOverviewRows.map((row, idx) => {
                  const isSelected =
                    row.location_id === selectedLocationId && row.supply_type === selectedSupplyType;
                  const isCritical = row.status === 'CRITICAL';

                  return (
                    <tr
                      key={`${row.location_id}-${row.supply_type}-${idx}`}
                      style={{
                        borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
                        background: isSelected
                          ? 'rgba(234, 179, 8, 0.08)'
                          : isCritical
                          ? 'rgba(239, 68, 68, 0.05)'
                          : 'transparent',
                        transition: 'background 0.2s ease',
                        cursor: 'pointer'
                      }}
                      onClick={() => handleSelectPreset(row.location_id, row.supply_type)}
                    >
                      {/* Location */}
                      <td style={{ padding: '12px 16px', fontWeight: 600, color: '#fff' }}>
                        <div>{row.location_name}</div>
                        <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>
                          {row.location_type} • {row.terrain}
                        </div>
                      </td>

                      {/* Supply */}
                      <td style={{ padding: '12px 16px', color: '#eab308', fontWeight: 600 }}>
                        {row.supply_type}
                      </td>

                      {/* Inventory */}
                      <td style={{ padding: '12px 16px' }} className="font-mono">
                        <strong style={{ color: isCritical ? '#ef4444' : '#fff' }}>
                          {row.current_inventory.toLocaleString()}
                        </strong>{' '}
                        <span style={{ fontSize: '0.76rem', color: 'var(--text-dim)' }}>{row.unit}</span>
                      </td>

                      {/* Avg Burn */}
                      <td style={{ padding: '12px 16px' }} className="font-mono">
                        {row.average_daily_consumption !== null
                          ? `${row.average_daily_consumption.toFixed(1)}/d`
                          : 'N/A'}
                      </td>

                      {/* Days Supply */}
                      <td style={{ padding: '12px 16px' }} className="font-mono">
                        <span
                          style={{
                            fontWeight: 700,
                            color:
                              row.days_of_supply === null
                                ? '#9ca3af'
                                : row.days_of_supply < 2
                                ? '#ef4444'
                                : row.days_of_supply < 4
                                ? '#f97316'
                                : row.days_of_supply <= 7
                                ? '#eab308'
                                : '#10b981'
                          }}
                        >
                          {row.days_of_supply_display}
                        </span>
                      </td>

                      {/* Reorder Point */}
                      <td style={{ padding: '12px 16px' }} className="font-mono">
                        <span style={{ color: 'var(--text-muted)' }}>
                          {row.reorder_point !== null ? row.reorder_point.toLocaleString() : 'N/A'}
                        </span>
                      </td>

                      {/* Status */}
                      <td style={{ padding: '12px 16px' }}>
                        <span
                          className={`badge ${
                            row.status === 'CRITICAL'
                              ? 'badge-danger'
                              : row.status === 'HIGH_RISK'
                              ? 'badge-warning'
                              : row.status === 'AT_RISK'
                              ? 'badge-warning'
                              : 'badge-success'
                          }`}
                          style={{ fontSize: '0.68rem' }}
                        >
                          {row.status}
                        </span>
                        {row.reorder_required && (
                          <span
                            className="badge badge-danger"
                            style={{ fontSize: '0.62rem', marginLeft: '6px' }}
                          >
                            REORDER
                          </span>
                        )}
                      </td>

                      {/* Action */}
                      <td style={{ padding: '12px 16px', textAlign: 'center' }}>
                        <button
                          onClick={e => {
                            e.stopPropagation();
                            handleSelectPreset(row.location_id, row.supply_type);
                          }}
                          className="btn-secondary"
                          style={{ padding: '4px 10px', fontSize: '0.75rem' }}
                        >
                          Inspect <ArrowRight size={12} />
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
