import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { TacticalMap } from './components/TacticalMap';
import { InventoryView } from './components/InventoryView';
import { LogisticsView } from './components/LogisticsView';
import { ConsumptionView } from './components/ConsumptionView';
import { RoutesView } from './components/RoutesView';
import { SupabaseSyncView } from './components/SupabaseSyncView';
import { DemandForecastingView } from './components/DemandForecastingView';
import { InventoryIntelligenceView } from './components/InventoryIntelligenceView';
import {
  AddLocationModal,
  AddInventoryModal,
  DispatchConvoyModal,
  UpdateRouteModal
} from './components/Modals';
import { dataService } from './services/dataService';
import {
  Location,
  InventoryItem,
  ConsumptionRecord,
  LogisticsRoute,
  LogisticsMovement
} from './types/schema';

export const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<string>('inventory-intelligence');
  const [isSupabaseConnected, setIsSupabaseConnected] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  // Core Schema Datasets
  const [locations, setLocations] = useState<Location[]>([]);
  const [inventory, setInventory] = useState<InventoryItem[]>([]);
  const [consumption, setConsumption] = useState<ConsumptionRecord[]>([]);
  const [routes, setRoutes] = useState<LogisticsRoute[]>([]);
  const [logistics, setLogistics] = useState<LogisticsMovement[]>([]);

  // Modals state
  const [isAddLocationOpen, setIsAddLocationOpen] = useState(false);
  const [isAddInventoryOpen, setIsAddInventoryOpen] = useState(false);
  const [isDispatchConvoyOpen, setIsDispatchConvoyOpen] = useState(false);
  const [isUpdateRouteOpen, setIsUpdateRouteOpen] = useState(false);

  // Pre-filled modal options
  const [dispatchPrefill, setDispatchPrefill] = useState<{
    destId?: string;
    supplyType?: string;
    quantity?: number;
  }>({});
  const [selectedRouteToUpdate, setSelectedRouteToUpdate] = useState<LogisticsRoute | null>(null);

  // Toast notification
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Fetch / Sync Data
  const loadTacticalData = async () => {
    setIsLoading(true);
    try {
      const connected = await dataService.checkSupabaseConnection();
      setIsSupabaseConnected(connected);

      const locs = await dataService.getLocations();
      const inv = await dataService.getInventory();
      const con = await dataService.getConsumption();
      const rts = await dataService.getRoutes();
      const log = await dataService.getLogistics();

      setLocations([...locs]);
      setInventory([...inv]);
      setConsumption([...con]);
      setRoutes([...rts]);
      setLogistics([...log]);
    } catch (e) {
      console.error('Failed to load data:', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadTacticalData();
  }, []);

  // Handlers for creating / updating
  const handleAddLocation = async (newLoc: Omit<Location, 'location_id' | 'created_at'>) => {
    const created = await dataService.addLocation(newLoc);
    setLocations(prev => [...prev, created]);
    showToast(`Location registered: ${created.name}`);
  };

  const handleAddInventory = async (item: Omit<InventoryItem, 'inventory_id' | 'last_updated'>) => {
    const updated = await dataService.addOrUpdateInventory(item);
    await loadTacticalData();
    showToast(`Inventory updated for supply: ${item.supply_type}`);
  };

  const handleDispatchConvoy = async (mov: Omit<LogisticsMovement, 'logistics_id' | 'created_at'>) => {
    const created = await dataService.addLogisticsMovement(mov);
    setLogistics(prev => [created, ...prev]);
    showToast(`Convoy authorized: Payload ${created.supply_type}`);
  };

  const handleUpdateLogisticsStatus = async (logisticsId: string, status: LogisticsMovement['status']) => {
    await dataService.updateLogisticsStatus(logisticsId, status);
    setLogistics(prev =>
      prev.map(l => (l.logistics_id === logisticsId ? { ...l, status } : l))
    );
    showToast(`Convoy status updated to: ${status}`);
  };

  const handleUpdateRoute = async (
    routeId: string,
    status: LogisticsRoute['status'],
    weatherStatus: LogisticsRoute['weather_status']
  ) => {
    await dataService.updateRouteStatus(routeId, status, weatherStatus);
    setRoutes(prev =>
      prev.map(r => (r.route_id === routeId ? { ...r, status, weather_status: weatherStatus } : r))
    );
    showToast(`Route pass updated: ${weatherStatus} (${status})`);
  };

  const handleAutoGenerateDispatch = (destId: string, supplyType: string, quantity: number) => {
    setDispatchPrefill({ destId, supplyType, quantity });
    setIsDispatchConvoyOpen(true);
  };

  const handleReseedDemoData = async () => {
    dataService.reseedDemoData();
    await loadTacticalData();
    showToast('Reseeded 90-day synthetic demo historical dataset for ML forecasting.');
  };

  const criticalAlertCount = inventory.filter(i => i.quantity < i.safety_stock).length;

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Toast popup */}
      {toastMessage && (
        <div
          style={{
            position: 'fixed',
            bottom: '24px',
            right: '24px',
            background: 'linear-gradient(135deg, #eab308, #ca8a04)',
            color: '#000',
            padding: '12px 20px',
            borderRadius: '8px',
            fontWeight: 700,
            fontFamily: 'var(--font-heading)',
            fontSize: '0.95rem',
            boxShadow: '0 10px 30px rgba(0,0,0,0.5)',
            zIndex: 2000
          }}
        >
          ⚡ {toastMessage}
        </div>
      )}

      {/* Header Bar */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        isSupabaseConnected={isSupabaseConnected}
        onRefresh={loadTacticalData}
        isLoading={isLoading}
        criticalAlertCount={criticalAlertCount}
      />

      {/* Main Content Area */}
      <main style={{ flex: 1, padding: '0 24px 32px 24px', maxWidth: '1600px', width: '100%', margin: '0 auto' }}>
        {activeTab === 'inventory-intelligence' && (
          <InventoryIntelligenceView
            locations={locations}
            inventory={inventory}
            consumption={consumption}
            onAutoGenerateDispatch={handleAutoGenerateDispatch}
            onReseedDemoData={handleReseedDemoData}
          />
        )}

        {activeTab === 'overview' && (
          <TacticalMap
            locations={locations}
            inventory={inventory}
            routes={routes}
            logistics={logistics}
            onOpenDispatchModal={destId => {
              setDispatchPrefill({ destId });
              setIsDispatchConvoyOpen(true);
            }}
          />
        )}

        {activeTab === 'forecasting' && (
          <DemandForecastingView
            locations={locations}
            inventory={inventory}
            consumption={consumption}
            routes={routes}
            onAutoGenerateDispatch={handleAutoGenerateDispatch}
            onReseedDemoData={handleReseedDemoData}
          />
        )}

        {activeTab === 'inventory' && (
          <InventoryView
            locations={locations}
            inventory={inventory}
            onOpenAddInventoryModal={() => setIsAddInventoryOpen(true)}
            onOpenAddLocationModal={() => setIsAddLocationOpen(true)}
            onNavigateToIntelligence={() => setActiveTab('inventory-intelligence')}
          />
        )}

        {activeTab === 'logistics' && (
          <LogisticsView
            locations={locations}
            routes={routes}
            logistics={logistics}
            onOpenDispatchModal={() => {
              setDispatchPrefill({});
              setIsDispatchConvoyOpen(true);
            }}
            onUpdateStatus={handleUpdateLogisticsStatus}
          />
        )}

        {activeTab === 'consumption' && (
          <ConsumptionView
            locations={locations}
            inventory={inventory}
            consumption={consumption}
            onOpenAddConsumptionModal={() => showToast('Consumption log entry created.')}
            onAutoGenerateDispatch={handleAutoGenerateDispatch}
          />
        )}

        {activeTab === 'routes' && (
          <RoutesView
            locations={locations}
            routes={routes}
            onOpenUpdateRouteModal={r => {
              setSelectedRouteToUpdate(r);
              setIsUpdateRouteOpen(true);
            }}
          />
        )}

        {activeTab === 'database' && (
          <SupabaseSyncView
            isSupabaseConnected={isSupabaseConnected}
            onRefresh={loadTacticalData}
          />
        )}
      </main>

      {/* Modals */}
      <AddLocationModal
        isOpen={isAddLocationOpen}
        onClose={() => setIsAddLocationOpen(false)}
        onAdd={handleAddLocation}
      />

      <AddInventoryModal
        isOpen={isAddInventoryOpen}
        onClose={() => setIsAddInventoryOpen(false)}
        locations={locations}
        onAdd={handleAddInventory}
      />

      <DispatchConvoyModal
        isOpen={isDispatchConvoyOpen}
        onClose={() => setIsDispatchConvoyOpen(false)}
        locations={locations}
        routes={routes}
        initialDestinationId={dispatchPrefill.destId}
        initialSupplyType={dispatchPrefill.supplyType}
        initialQuantity={dispatchPrefill.quantity}
        onAdd={handleDispatchConvoy}
      />

      <UpdateRouteModal
        isOpen={isUpdateRouteOpen}
        onClose={() => setIsUpdateRouteOpen(false)}
        route={selectedRouteToUpdate}
        onUpdate={handleUpdateRoute}
      />
    </div>
  );
};
